[build]
  # Directory to build from
  publish = "."
  
  # Build command (not needed for static HTML site)
  command = ""

[build.environment]
  # Node version for build (if needed in future)
  NODE_VERSION = "18"

# Redirect rules for single page application behavior
[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"